[package]
name = "ProxyTools-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "proxy"
path = "src/bin/proxy.rs"

[[bin]]
name = "noproxy"
path = "src/bin/noproxy.rs"

[dependencies]
